### ISSUE TITLE
Rename course number in the project name

### ISSUE THREAD

**Issue by ibnesayeed** [phonedude/cs531-f18#1]
Should `cs595-f18` project name be changed to `cs531-f18`? I know it will automatically add a redirect on GitHub repo, but not sure about an automated redirect in the GitHub pages URI.

**Comment by phonedude** [comment]
renamed.  the repo redirects, but the page URI doesn't:

% curl -I https://phonedude.github.io/cs595-f18/
HTTP/1.1 404 Not Found
Server: GitHub.com
Content-Type: text/html; charset=utf-8
ETag: "590ba6fa-239c"
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
X-GitHub-Request-Id: 6FA8:772D:F1A673:143F09F:5B86128E
Content-Length: 9116
Accept-Ranges: bytes
Date: Wed, 29 Aug 2018 03:27:11 GMT
